### ISSUE TITLE
Cart::onRemove doesn't work with some properties in cartPositionItem

### ISSUE THREAD

**Issue by Borowing** [oc-shopaholic/oc-shopaholic-plugin#209]
Hi,
why i can't remove an item from the cart if this item has some properties ?

**Comment by kharanenka** [comment]
If you send **"offer_id"** in request, then cart position that needs to be deleted will be searched by "offer_id" and properties. This logic is used in order to be able to add same offer, but with different properties.

To delete and update, you can send **"id"** field instead of "offer_id". In "id" field you need to set **id of cart position**.  You also need to send **"type"** field  **'type': 'position'**,

For example:
Your variant ([2,10] - array with offer_id)
```javascript
//Prepare array with offers ID
var data = {
    'cart': [2,10],
    'shipping_type_id': 4
};

//Send ajax request and update cart items
$.request('Cart::onRemove', {
    'data': data,
    'update': {'cart-items': '.cart-item-wrapper'}
});
```

New way ([12,14] - array with cart position ID's):
```javascript
//Prepare array with offers ID
var data = {
    'cart': [12,14],
    'type': 'position',
    'shipping_type_id': 4
};

//Send ajax request and update cart items
$.request('Cart::onRemove', {
    'data': data,
    'update': {'cart-items': '.cart-item-wrapper'}
});
```

**Comment by Borowing** [comment]
thank you, it works!!
