### ISSUE TITLE
При добавлении custom field через расширение торгового предложения, данное поле не доступно для импорта

### ISSUE THREAD

**Issue by ref** [oc-shopaholic/oc-shopaholic-plugin#243]
Расширяю по инструкции — http://shopaholic.one/docs#/modules/offer/extending/extending

Созданное свойство находится не в списке с полями базы данных (как например, если использовать плагин Properties), а на отдельной вкладке "Настройки", из-за чего невозможно с помощью импорта массово создавать ТП и заполнять свойство.

<img width="1181" alt="Screenshot 2020-01-24 at 15 43 27" src="https://user-images.githubusercontent.com/505388/73056001-943ead80-3ec0-11ea-84ff-31e8bd656ddb.png">

**Comment by kharanenka** [comment]
Fixed in Toolbox plugin. ([link](https://github.com/oc-shopaholic/oc-toolbox-plugin/commit/af617f48c1cd7bde7ad9dfb52656c48858c8d4b0))

Expansion of fields in CSV improt form is not accessible with using [backend.form.extendFields](https://octobercms.com/docs/plugin/extending#extending-backend-form) event. There are no events to extend CSV import fields. This is possible only if you extend controller config (importExportConfig config). An example of an extension is in Properties plugin (plugins/lovata/propertiesshopaholic/classes/event/product/ExtendProductControllerHandler.php file).
